### PR TITLE
Identifiers with configurable prefixes

### PR DESCRIPTION
**Pull request by tasdomas**
This is needed to be able to differentiate between tasks allocated using leo server and tpi/leo cli.

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Also useful for #726 and `cml-` prefixes, but I would argue that there is no need to differentiate `leo-server` from the `leo` command-line tool.

**Review by 0x2b3bfa0 — COMMENTED** [review]
Why enforce the 3 character length requirement? Alternatively, can we just have some `const` prefix values to choose from? E.g. 

```go
type prefix string

const (
    prefixTPI prefix = "tpi"
    prefixLEO prefix = "leo"
    prefixCML prefix = "cml"
)
```

**Comment by tasdomas** [comment]
> Why enforce the 3 character length requirement? Alternatively, can we just have some `const` prefix values to choose from? E.g.
> 
> ```go
> type prefix string
> 
> const (
>     prefixTPI prefix = "tpi"
>     prefixLEO prefix = "leo"
>     prefixCML prefix = "cml"
> )
> ```

I don't see a big difference - keeping it a simple string seems slightly more extendable.

**Review by 0x2b3bfa0 — APPROVED** [review]
To my mind, the “flexibility” provided by acepting arbitrary prefixes is a bit of a footcannon, but... 🤷🏼‍♂️

**Pull request merged**
