### PR TITLE
Migrate to aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Part of https://github.com/iterative/terraform-provider-iterative/issues/185

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 
Why do you not include this work inside https://github.com/iterative/terraform-provider-iterative/pull/187?
It depends on this and the reason the create this PR is to be able to support https://github.com/iterative/terraform-provider-iterative/pull/187, right?

**Comment by 0x2b3bfa0** [comment]
Yes, I separated it just to keep two commits after squash+merge and be able to `blame` better in the future.

**Review by DavidGOrtega — APPROVED** [review]
👍 

PD I do not fully see why update if we do not need it but Its OK

**Comment by 0x2b3bfa0** [comment]
https://github.com/iterative/terraform-provider-iterative/pull/187#issuecomment-916794514

**Pull request merged**
