### PR TITLE
Fix nil pointer derreference on AWS resource destroy

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
~Probably discovered by @DavidGOrtega on https://github.com/iterative/terraform-provider-iterative/pull/187#issuecomment-916046982.~ Unrelated: serendipity discovery by @0x2b3bfa0

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
Why are you splitting this a a separate PR instead of add it to https://github.com/iterative/terraform-provider-iterative/pull/187 ?

**Comment by 0x2b3bfa0** [comment]
Because it's unrelated and predates #187, but we can merge it to #187 if you want.

**Comment by DavidGOrtega** [comment]
In any case I did not discover this. I did not had such error in https://github.com/iterative/terraform-provider-iterative/pull/187#issuecomment-916046982

**Review by DavidGOrtega — APPROVED** [review]
👍 lgtm

**Pull request merged**
