### PR TITLE
Encrypt credentials with sealed box

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
* [x] Implementation
* [x] Tests 
* [x] JavaScript logic: see https://github.com/iterative/terraform-provider-iterative/pull/721#issuecomment-1317081083
* [x] OpenAPI handler to retrieve the public key

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@tasdomas, wrote this ~out of sheer boredom~ to address https://github.com/iterative/terraform-provider-iterative/pull/708#issuecomment-1303654847; feel free to take a look if you deem it useful

**Comment by dacbd** [comment]
@0x2b3bfa0 can you save me some googling and share a cli example of wrapping the credentials?

**Review by tasdomas — CHANGES_REQUESTED** [review]
I think this is a great idea, but we should hold off on landing this until we have a working experiment UI.

Also, this needs to be moved to the [leo-server](github.com/iterative/leo-server) repo.

**Comment by 0x2b3bfa0** [comment]
Moved permanently to https://github.com/iterative/leo-server/pull/9

**Pull request closed without merging**
