### PR TITLE
Increase test timeout

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Continuation of https://github.com/iterative/terraform-provider-iterative/pull/649#issuecomment-1234525333

### CODE REVIEW

**Comment by tasdomas** [comment]
`30s` -> `29s` increase?

**Comment by 0x2b3bfa0** [comment]
As per https://github.com/iterative/terraform-provider-iterative/pull/650/commits/d8e005782d35a818502ff84bdf72f6ca3f973b98, I wanted to _“decrease timeout by 1 second to reproduce [the] issue”_

**Comment by 0x2b3bfa0** [comment]
...and couldn't reproduce the issue: now tests are passing 😅

**Comment by 0x2b3bfa0** [comment]
Unable to reproduce anymore, closing...

**Pull request closed without merging**
