### PR TITLE
Simplify log format

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
https://www.notion.so/TPI-0-9-feedback-99cff02fa4b44dd9815767d953616bd1?d=bbf17979200844c2b7b8a7785ca08693#6bc5b057cfc94239aef1a10cfcdbc7e4

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
This maybe does not solves the proposal as far as I understand it

**Comment by 0x2b3bfa0** [comment]
Yes, it doesn't _solve_ the proposal. It's just a small step in that direction.

**Comment by DavidGOrtega** [comment]
Indeed I like it to have the date.
IMHO we need to bring customised logs with backends

**Comment by 0x2b3bfa0** [comment]
I also like it to have the date, similarly to GitHub Actions and any other CI/CD engine logs. 🤷🏼 Still, noise versus functionality is an open debate.

**Comment by DavidGOrtega** [comment]
I do not consider date noise so I do not like this PR

**Review by casperdcl — COMMENTED** [review]
don't see much point in removing datetime tbh.

**Pull request closed without merging**
