### PR TITLE
Update nvidia container support package

### PR DESCRIPTION
**Pull request by aliabbasjaffri**
Replaced the deprecated nvidia package with the new `nvidia-container-utils` as mentioned in the official [documentation](https://github.com/NVIDIA/nvidia-docker/tree/36e7a11c52f300668099ee500791e07302810007)

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@aliabbasjaffri, can you please update also golden tests with `go test iterative -update`? 🙏🏼

**Comment by aliabbasjaffri** [comment]
Sorry for asking the dumb question here, but i'm new to this. How would i update the golden tests?

**Comment by 0x2b3bfa0** [comment]
By running `go test ./iterative -update` as stated on https://github.com/iterative/terraform-provider-iterative/pull/688#issuecomment-1271417049

**Comment by aliabbasjaffri** [comment]
@0x2b3bfa0 golden tests generated and updated!

**Comment by 0x2b3bfa0** [comment]
Thank you very much, @aliabbasjaffri! 🙏🏼

**Comment by aliabbasjaffri** [comment]
@0x2b3bfa0 Seems like auto-merge didn't work! :(

**Review by 0x2b3bfa0 — APPROVED** [review]
Forgot to approve 🙈

**Pull request merged**
