### PR TITLE
Add a hidden leo subcommand `report` to send live-metrics reports to studio.

### PR DESCRIPTION
**Pull request by tasdomas**
This still needs to be carefully integrated into the machine script (we don't want to trigger report sending for
users using leo or tpi directly).

### CODE REVIEW

**Review by casperdcl — CHANGES_REQUESTED** [review]
Existential dilemma: does this business logic really belong in this repo?

**Comment by 0x2b3bfa0** [comment]
Existential dilemma: do we need yet another `curl` doppelganger? It looks nicer on #734, though.

**Comment by dacbd** [comment]
> Existential dilemma: does this business logic really belong in this repo?

agreed I think we can just embed the required logic in the script that we generate.

**Comment by tasdomas** [comment]
> > Existential dilemma: does this business logic really belong in this repo?
> 
> agreed I think we can just embed the required logic in the script that we generate.
The machine script or the script generated by light experiments?

**Comment by 0x2b3bfa0** [comment]
Superseded by #735 🙃

**Pull request closed without merging**
