### PR TITLE
Document DescribeInstanceTypeOfferings permission

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
* https://github.com/iterative/terraform-provider-iterative/pull/670#pullrequestreview-1134317993

### CODE REVIEW

**Review by tasdomas — APPROVED** [review]

**Comment by dacbd** [comment]
I dont think this is used by task...?
https://cml.dev/doc/ref/runner#common-permissions

**Comment by 0x2b3bfa0** [comment]
No, it's not

**Comment by 0x2b3bfa0** [comment]
Those permissions are for both `task` and `machine` because somebody in a meeting<sup>[citation needed]</sup> found it convenient.

**Comment by dacbd** [comment]
`data "aws_iam_policy_document" "task" {`
`+  "ec2:DescribeInstanceTypeOfferings",`

**Comment by dacbd** [comment]
https://github.com/iterative/cml.dev/pull/337

**Pull request merged**
