### PR TITLE
Fix k8s test fixture

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
#271 broke the tests because GitHub won't allow users to pass a secret between jobs. 🤦🏼‍♂️

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Merging to test...

**Comment by 0x2b3bfa0** [comment]
@casperdcl, do you know a better solution for https://github.com/iterative/terraform-provider-iterative/pull/271 than #274? I don't quite like the idea of having to test a provider outside the matrix just because of this.

**Comment by casperdcl** [comment]
well could encode & decode using e.g. `base64` but I think the slight repetition here is fine... especially since this provider is quite different from the rest of the matrix.

**Review by casperdcl — COMMENTED** [review]
well could encode & decode using e.g. `base64` but I think the slight repetition here is fine... especially since this provider is quite different from the rest of the matrix.

**Comment by 0x2b3bfa0** [comment]
> _well could encode & decode using e.g. `base64`_

I hope you didn't mean that. 😈 Plain text secrets are in plain text no matter where they're ASCII, Base64 or ROT-13.

Moreover, the GitHub Actions secret masking system will also search for the Base64 version of secrets.

**Pull request merged**
