### PR TITLE
Resource Cml runner failproof dependencies

### LINKED ISSUE #167: Dynamically detect CML AMI availability
Coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/868138422177513533)

For some reason that image is not accessing the ```cml-runner``` command.

### PR DESCRIPTION
**Pull request by DavidGOrtega**
To prevent not installing the stack by any meaning, the new strategy checks if a file at /var/logs/cml_stack.log exists to decide if the stack needs to be installed or not. So CML AMIs should have that file after setup.
We also use the setup.sh with go-bindata to remove duplicated code

- closes #167 
 - Dryer setup introducing go-bindata
 - Better base64 logic and test
 - Faster setup removing docker nvidia-smi test
 - Dryer template
 - Adds restyle config to avoid golden

### CODE REVIEW

**Comment by casperdcl** [comment]
fixes https://github.com/iterative/cml/issues/670

**Comment by 0x2b3bfa0** [comment]
^fixes^mitigates^

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 reviewed?

**Comment by 0x2b3bfa0** [comment]
⏳

**Pull request merged**
