### PR TITLE
Rename --tf_resource to --tf-resource for consistency

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
⚠️ To be released after iterative/cml#554; also migrates Kubernetes to the new image tag convention.

### CODE REVIEW

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]
I can not see that change effectively in the other repo?

.default('tf_resource')
    .hide('tf_resource')

the parameter is hidden and should be aliased

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 this should be released once CML is released. Am I correct?

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, yes, absolutely.

**Review by DavidGOrtega — APPROVED** [review]
🚀 👍 
This only can be released after CML's 
https://github.com/iterative/cml/pull/554. release

**Comment by 0x2b3bfa0** [comment]
[Done!](https://github.com/iterative/cml/releases/tag/v0.4.4)

**Pull request merged**
