### PR TITLE
Simplify Readme

### PR DESCRIPTION
**Pull request by dacbd**
Closes: #556

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Worth extending to the `docs` directory?

```console
$ git grep TF_LOG_PROVIDER
README.md:TF_LOG_PROVIDER=INFO terraform apply
README.md:TF_LOG_PROVIDER=INFO terraform refresh
README.md:TF_LOG_PROVIDER=INFO terraform show
README.md:TF_LOG_PROVIDER=INFO terraform destroy
README.md:The [getting started guide](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/getting-started) has some more information. In case of errors, extra debugging information is available using `TF_LOG_PROVIDER=DEBUG` instead of `INFO`.
docs/guides/authentication.md:TF_LOG_PROVIDER=INFO terraform apply
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform apply
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform refresh
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform show
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform destroy
docs/guides/getting-started.md:Use `TF_LOG_PROVIDER=DEBUG` in lieu of `INFO` to increase verbosity for debugging. See the [logging docs](https://www.terraform.io/plugin/log/managing) for a full list of options.

**Review by 0x2b3bfa0 — COMMENTED** [review]
Worth extending to the `docs` directory?

```console
$ git grep TF_LOG_PROVIDER
README.md:TF_LOG_PROVIDER=INFO terraform apply
README.md:TF_LOG_PROVIDER=INFO terraform refresh
README.md:TF_LOG_PROVIDER=INFO terraform show
README.md:TF_LOG_PROVIDER=INFO terraform destroy
README.md:The [getting started guide](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/getting-started) has some more information. In case of errors, extra debugging information is available using `TF_LOG_PROVIDER=DEBUG` instead of `INFO`.
docs/guides/authentication.md:TF_LOG_PROVIDER=INFO terraform apply
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform apply
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform refresh
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform show
docs/guides/getting-started.md:$ TF_LOG_PROVIDER=INFO terraform destroy
docs/guides/getting-started.md:Use `TF_LOG_PROVIDER=DEBUG` in lieu of `INFO` to increase verbosity for debugging. See the [logging docs](https://www.terraform.io/plugin/log/managing) for a full list of options.

**Comment by DavidGOrtega** [comment]
I thought the same @dacbd But I also found interesting the one line idea very good. Why?
If you overlook to setup that ENV var logs wont happen however is very easy to paste the TF command with the logs... Also the smart reader will know...
Im totally divided about which is the best option, unable to vote 😁

**Review by casperdcl — CHANGES_REQUESTED** [review]
please add to the `docs/` too... :+1:

- pro: at a glance, looks tidier
- con: we don't remind people to `export` on each terminal restart... should we? con: if we explain it, it's painfully distracting
- not-a-con: users probably won't miss it since we mention it right next to `terraform init`

:-1: ... or maybe we just close this unmerged and accept most users are advanced enough to appreciate the docs using this on every command rather than one-export-somewhere-hard-to-find-and-a-lengthy-explanation-about-the-convept-of-exports?

**Comment by 0x2b3bfa0** [comment]
This is an [xyproblem](https://xyproblem.info) at many levels: _users_ should not _need_ to use this environment variable _at all_ when using Terraform as intended.

Given that we require it to be set, the current repetition might be easier to understand for novice users. It's ugly, but it's ugly for a reason. 🤷🏼‍♂️

**Comment by dacbd** [comment]
Sure, Just changes based on feedback, if users get confused or don't use it we can always add them back and think of other ways to push it.

**Review by casperdcl — APPROVED** [review]
meh

**Pull request merged**
