### PR TITLE
Discord link update - third times a charm - Update README.md

### PR DESCRIPTION
**Pull request by jendefig**
Per last week's release meeting and decision to combine CML and TPI into one channel.  Using Elle's old link even though it's longer, because it has analytic history already.

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
🙈

**Comment by DavidGOrtega** [comment]
@jendefig @casperdcl do we have here an agreement?

**Comment by casperdcl** [comment]
Pending @shcheklein feedback at https://github.com/iterative/cml.dev/pull/199 :)

**Comment by casperdcl** [comment]
resolved upstream :)

**Comment by 0x2b3bfa0** [comment]
🎉

**Pull request merged**
