### PR TITLE
Reboot to enable nvidia

### PR DESCRIPTION
**Pull request by DavidGOrtega**
Seems that nvidia needs to be rebooted now. So we are rebooting and enabling cml after reboot, additionally we are adding the latest nvidia ppa.

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 ready please test 🙏

**Comment by DavidGOrtega** [comment]
Ok this should not work in aws, however... it does.
We do no use elastic IPs and in a naive test TF is giving me this IP 18.144.XXX.XXX however when I get in the machine it clearly says:

ubuntu@ip-172-31-XXX-XXX which is obviously different, however for some reason it works and sticks...

**Comment by 0x2b3bfa0** [comment]
> _Ok this should not work in aws, however... it does._

If you mean because of #44, yes, it wouldn't

> clearly says: `ubuntu@ip-172-31-XXX-XXX` which is obviously different

This is not the public address, but the private one: `172.31.0.0/16` is one of the 16 class B private networks in the "172" block.

**Comment by DavidGOrtega** [comment]
I overlooked the 31 because of #44 seems to be working in AWS too!

**Comment by DavidGOrtega** [comment]
image

**Comment by 0x2b3bfa0** [comment]
There are some nuances:
* #44 is about stopping and starting an EC2 instance; that changed, changes, and will change the address each time.
* #129 is about rebooting the operating system without altering the machine state, and that doesn't change the address.

**Comment by DavidGOrtega** [comment]
> There are some nuances:

To me they should be aligned like in Azure but I do not design AWS 😄

**Review by 0x2b3bfa0 — APPROVED** [review]
Actually, the image boots with `5.4.0-1047-azure` but drivers get installed for `5.4.0-1048-azure` so rebooting is the only way of loading the installed drivers.

Linus, I'm thinking exactly that.

**Pull request merged**
