### PR TITLE
Debug the instance IP prior to awaiting the runner

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
This would be extremely useful for debugging some connection issues.

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 do you think so?
I mean, that log will only be visible if we setup the debug level as env variable right? Or maybe is there another way?

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, yes, the nice thing is that we can handle all that through the environment and sedn the debug output to a file for further investigation. Please check [this workflow](https://github.com/iterative/cml/issues/484#issuecomment-828823161) for an example.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 got it!

**Review by DavidGOrtega — APPROVED** [review]
lgtm

**Pull request merged**
