### PR TITLE
Add support for Azure metadata (tags)

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Part of https://github.com/iterative/terraform-provider-iterative/issues/185

### CODE REVIEW

**Review by DavidGOrtega — COMMENTED** [review]
Tags does not seem to be created

image


Here is the file:

```tf
terraform {
  required_providers {
    iterative = {
      source = "github.com/iterative/iterative"
    }
  }
}

provider "iterative" {}

resource "iterative_cml_runner" "runner-gh-11" {
    metadata = {
      project = "example"
      creator = "anybody"
    }

    token = "XXX"
    repo = "XXX"
    driver = "gitlab"
    labels = "azure"
    idle_timeout = 0

    cloud = "azure"
    region = "us-west"
    instance_type = "Standard_F8s_v2"
    spot = true
    ssh_private = "XXX"
}
```

Im expecting to see project and creator tags

**Comment by 0x2b3bfa0** [comment]
That's what I see when navigating to https://portal.azure.com/#blade/HubsExtension/TagsBlade:
Captura de pantalla 2021-09-10 a las 12 23 19

**Comment by DavidGOrtega** [comment]
Not sure what do you mean. Can you please check that tags are created in your resources?
As far asI can state at least in the UI do not appear.

**Comment by 0x2b3bfa0** [comment]
> Not sure what do you mean. Can you please check that tags are created in your resources?
> As far asI can state at least in the UI do not appear.

I mean that, after _you_ ran `terraform apply` tags were created (globally) and you can see them at  https://portal.azure.com/#blade/HubsExtension/TagsBlade and on every resource, as per [my screenshot](https://github.com/iterative/terraform-provider-iterative/pull/191#issuecomment-916798931).

The resource group itself, shown in [your screenshot](https://github.com/iterative/terraform-provider-iterative/pull/191#pullrequestreview-751251668) wasn't being tagged, but wa can also tag it: see https://github.com/iterative/terraform-provider-iterative/pull/191/commits/896d1f3b1f7e828010c7865f547486bdcb044dab

**Review by DavidGOrtega — APPROVED** [review]
lgtm 🚀

**Pull request merged**
